### ISSUE TITLE
Binary?

### ISSUE THREAD

**Issue by jsa-aerial** [weavejester/haslett#11]
It looks like the 'out of the box' wire protocol is string/text based. But this seems lightweight enough that it wouldn't preclude a binary protocol if it were conjured up and provided, correct? I have something for that, but just checking if there are any gotchas to look out for.

I guess this is more of a question than an issue

**Comment by weavejester** [comment]
Haslett includes formatters for Transit, edn and JSON, with Transit being the recommended option. You can easily write your own formatter by implementing the [haslett.format/Format](https://github.com/weavejester/haslett/blob/master/src/haslett/format.cljs#L8) protocol.

**Comment by jsa-aerial** [comment]
sounds like the answer I expected and was hoping for!
