### ISSUE TITLE
Question: How would you implement a "on-message-handler"

### ISSUE THREAD

**Issue by smoes** [weavejester/haslett#12]
I'm thinking about the best-practice/idiomatic way for constantly pulling messages from the channel, like, implementing handler-functionality. That is, everytime an incoming message appears a function (the handler) is called. Must I periodically check the channel for new messages? 

Thanks for your help in advance!

**Comment by weavejester** [comment]
Just setup a go-loop:

```clojure
(go-loop (handler (<! (:source stream))))
```

**Comment by smoes** [comment]
Oh boy, most of the type I seem attracted the most complicated constructs first :man_facepalming: 
Thank you very much for the fast answer, works like a charm!
