### ISSUE TITLE
Error handling examples

### ISSUE THREAD

**Issue by hoopes** [weavejester/haslett#13]
Hi, I was wondering if there was a best practice for error handling with this library. There is the other issue about the 500 on connect, and mentions the `close-status` promise channel, but I think an example of that would be great.

Additionally, an example of handling disconnects and auto-reconnects would be super useful for me, at the moment :). Like, I have a `go-loop` for receiving messages...on a disconnect, does the `source` and `sink` get an empty message or something, or a disconnect of some kind? I'm working on reading the code, but a quick example would (in my opinion, for whatever that's worth) be hugely helpful.

Thanks for reading!

**Comment by weavejester** [comment]
When a core.async channel is closed, it returns `nil` when you try and read from it. If that happens, you can read the `:close-status` promise channel in order to understand why the websocket was closed.

Adding a working example sounds fine, but it'll be a while before I can get around to it, as I'd ideally want to test the example works on different errors.

**Comment by hoopes** [comment]
Thanks for the hint! How about on failed connection - should I read the `:close-status` right after trying to connect to determine whether it succeeded or not, or should I check the `readyState` of the socket itself? Like (pseudocode):

```
conn-obj (<! (ws/connect url))

if (conn-obj.readyState < 2) { 
   (start-on-msg-listener)
}
else {
    sleep(1 second)
    recur to reconnect
}
```

There's no `peek` for core.async, right? 

Thanks again!

**Comment by hoopes** [comment]
Also, if there's a better forum for asking these question, please feel free to point me in the correct direction, not trying to violate any etiquette rules...

**Comment by weavejester** [comment]
I'm actually not completely sure. I can tell you how Haslett interfaces with websockets, as the code is just a thin wrapper, but I can't remember off the top of my head how the websocket API itself handles connection errors.

I recall that a disconnect will close the channel and add a value to the close-status channel; however, I'm not sure how a connection that fails to open will be handled. It's possible that Haslett needs a error promise channel to properly handle that (as suggested by #8).

When I next come to use websockets I'll look into it, but if you figure it out in the meantime, feel free to add an example to the end of this issue and I'll add it to the README.

**Comment by hoopes** [comment]
Thank you sir, much appreciated!

**Comment by weavejester** [comment]
Sorry I couldn't be more help!
