### ISSUE TITLE
Support for Clojure?

### ISSUE THREAD

**Issue by alex-dixon** [weavejester/haslett#3]
😃

**Comment by weavejester** [comment]
Not a priority for me I'm afraid. Maybe look at [Gniazdo](https://github.com/stylefruits/gniazdo) for Clojure support?

**Comment by alex-dixon** [comment]
Nice. Haven't seen that one. Definitely seems to have a similar zen w/r/t to haslett though it appears to be missing an `:uid` scheme like sente, edn or transit support, and this, which I think is positively brilliant and haven't seen elsewhere:
```
You can customize the behaviour further by supplying your own channels for the source and sink. This allows you to tune the channel buffer, and add tranducers:

(ws/connect "ws://echo.websocket.org"
            {:source (a/chan 10)
             :sink   (a/chan 10)})
```

Hypothetically, if you were to make a Clojure version, would you use the Jetty socket?

Very hypothetically, would you accept a PR along these lines?

My use case is a client that could run in CLJS (browser) and CLJ (server). Do you use gniazdo for such cases?

**Comment by weavejester** [comment]
I haven't ever had the need to run a WebSocket client from Clojure. I'm not sure what the best client library would be for this. Jetty seems a little heavyweight, but maybe the WebSocket client is separate from the web server.

Hypothetically I'd accept a PR, but I'd want to know which WebSocket client library is most suitable first, and I'm afraid this isn't something I personally need. But if someone submitted a good argument for which client library to use, then based a PR off that, then I could see myself accepting it. However, I'm a little worried about excess dependencies.
