### ISSUE TITLE
Support for passing protocol(s)

### ISSUE THREAD

**Issue by colindresj** [weavejester/haslett#9]
Would be nice to be able to pass some protocols when constructing the socket. Maybe something like:

```clj
(ws/connect "ws://echo.websocket.org" {:protocols ["some-ws-protocol"]})
```

Happy to put together a PR

**Comment by weavejester** [comment]
Sure, that sounds like a good idea.

**Comment by colindresj** [comment]
Pr here: https://github.com/weavejester/haslett/pull/10

**Comment by colindresj** [comment]
Thanks for the update @weavejester. Any chance you can release a new version with this?
